// Date: 26/10/2012 18:38:49
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package FunMod.cliente.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTvN64 extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
  
  public ModelTvN64()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 70);
      Shape1.addBox(0F, 0F, 0F, 12, 3, 12);
      Shape1.setRotationPoint(-6F, 18F, -6F);
      Shape1.setTextureSize(256, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 7, 58);
      Shape2.addBox(0F, 0F, 0F, 6, 1, 5);
      Shape2.setRotationPoint(-3F, 17F, -6F);
      Shape2.setTextureSize(256, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 30);
      Shape3.addBox(0F, 0F, 0F, 16, 1, 16);
      Shape3.setRotationPoint(-8F, 21F, -8F);
      Shape3.setTextureSize(256, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 50);
      Shape4.addBox(0F, 0F, 0F, 1, 15, 1);
      Shape4.setRotationPoint(7F, 9F, -8F);
      Shape4.setTextureSize(256, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 50);
      Shape5.addBox(0F, 0F, 0F, 1, 15, 1);
      Shape5.setRotationPoint(-8F, 9F, -8F);
      Shape5.setTextureSize(256, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 50);
      Shape6.addBox(0F, 0F, 0F, 1, 15, 1);
      Shape6.setRotationPoint(-8F, 9F, 7F);
      Shape6.setTextureSize(256, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 50);
      Shape7.addBox(0F, 0F, 0F, 1, 15, 1);
      Shape7.setRotationPoint(7F, 9F, 7F);
      Shape7.setTextureSize(256, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 30);
      Shape8.addBox(0F, 0F, 0F, 16, 1, 16);
      Shape8.setRotationPoint(-8F, 9F, -8F);
      Shape8.setTextureSize(256, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 45, 0);
      Shape9.addBox(0F, 0F, 0F, 10, 11, 10);
      Shape9.setRotationPoint(-5F, -2F, -5F);
      Shape9.setTextureSize(256, 128);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 0);
      Shape10.addBox(0F, 0F, 0F, 12, 12, 5);
      Shape10.setRotationPoint(-6F, -3F, -6F);
      Shape10.setTextureSize(256, 128);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
  }
  public void renderModel(float f1)
  {
	  Shape2.render(f1);
	  Shape1.render(f1);
	  Shape3.render(f1);
	  Shape4.render(f1);
	  Shape5.render(f1);
	  Shape6.render(f1);
	  Shape7.render(f1);
	  Shape8.render(f1);
	  Shape9.render(f1);
	  Shape10.render(f1);
  }
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity ll)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, ll);
  }

}
