// Date: 30/08/2012 21:10:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package FunMod.cliente.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLiving;
import net.minecraft.util.MathHelper;

public class ModelKoopa extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer head2;
    ModelRenderer eyes;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer shell1;
    ModelRenderer shell2;
    ModelRenderer rightshoes;
    ModelRenderer leftshoes;
  
  public ModelKoopa()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-5F, -8F, -4F, 6, 3, 4);
      head.setRotationPoint(2F, 19F, -2F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      head2 = new ModelRenderer(this, 0, 21);
      head2.addBox(-1F, 12F, -8F, 4, 2, 3);
      head2.setRotationPoint(-1F, 0F, 0F);
      head2.setTextureSize(64, 32);
      head2.mirror = true;
      setRotation(head2, 0F, 0F, 0F);
      eyes = new ModelRenderer(this, 9, 17);
      eyes.addBox(-4F, -1F, -4F, 6, 3, 1);
      eyes.setRotationPoint(1F, 9F, -1F);
      eyes.setTextureSize(64, 32);
      eyes.mirror = true;
      setRotation(eyes, 0F, 0F, 0F);
      body = new ModelRenderer(this, 8, 8);
      body.addBox(-4F, 0F, -2F, 4, 6, 2);
      body.setRotationPoint(2F, 13F, -3F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0.5576792F, 0F, 0F);
      rightarm = new ModelRenderer(this, 20, 8);
      rightarm.addBox(-3F, -2F, -2F, 1, 5, 1);
      rightarm.setRotationPoint(0F, 16F, -2F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, -0.0371786F, 0F, 0F);
      leftarm = new ModelRenderer(this, 20, 8);
      leftarm.addBox(-1F, -2F, -2F, 1, 5, 1);
      leftarm.setRotationPoint(3F, 16F, -2F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 8);
      rightleg.addBox(-2F, 0F, -2F, 1, 6, 1);
      rightleg.setRotationPoint(0F, 18F, 1F);
      rightleg.setTextureSize(64, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 8);
      leftleg.addBox(-2F, 0F, -2F, 1, 6, 1);
      leftleg.setRotationPoint(3F, 18F, 1F);
      leftleg.setTextureSize(64, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      shell1 = new ModelRenderer(this, 26, 0);
      shell1.addBox(0F, 0F, 0F, 6, 1, 6);
      shell1.setRotationPoint(-3F, 13F, -3F);
      shell1.setTextureSize(64, 32);
      shell1.mirror = true;
      setRotation(shell1, -0.8551081F, 0F, 0F);
      shell2 = new ModelRenderer(this, 28, 8);
      shell2.addBox(0F, -1F, 0F, 4, 2, 5);
      shell2.setRotationPoint(-2F, 13F, -2F);
      shell2.setTextureSize(64, 32);
      shell2.mirror = true;
      setRotation(shell2, -0.8551066F, 0F, 0F);
      rightshoes = new ModelRenderer(this, 0, 15);
      rightshoes.addBox(0F, 0F, 0F, 1, 1, 2);
      rightshoes.setRotationPoint(-2F, 23F, -2F);
      rightshoes.setTextureSize(64, 32);
      rightshoes.mirror = true;
      setRotation(rightshoes, 0F, 0F, 0F);
      leftshoes = new ModelRenderer(this, 0, 15);
      leftshoes.addBox(0F, 0F, 0F, 1, 1, 2);
      leftshoes.setRotationPoint(1F, 23F, -2F);
      leftshoes.setTextureSize(64, 32);
      leftshoes.mirror = true;
      setRotation(leftshoes, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.render(f5);
    head2.render(f5);
    eyes.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    shell1.render(f5);
    shell2.render(f5);
    rightshoes.render(f5);
    leftshoes.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ll)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, ll);
  }

  public void setLivingAnimations(EntityLiving par1EntityLiving, float f1, float f2, float f3)
  {

      leftleg.rotateAngleX = MathHelper.cos(f1 * 0.6662F) * 1.4F * f2;
      rightleg.rotateAngleX = MathHelper.cos(f1 * 0.6662F + (float)Math.PI) * 1.4F * f2;
  }
  
}
