// Date: 27/10/2012 22:51:04
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package FunMod.cliente.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSofa extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer head;
    ModelRenderer feet;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
  
  public ModelSofa()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 26, 19);
      Shape1.addBox(-1F, -1F, 0F, 2, 2, 2);
      Shape1.setRotationPoint(-7F, 17.1F, -2.7F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0.7853982F, 0F, 0F);
      
      Shape2 = new ModelRenderer(this, 26, 19);
      Shape2.addBox(0F, -1F, 0F, 2, 2, 2);
      Shape2.setRotationPoint(6F, 17.1F, -2.7F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0.7853982F, 0F, 0F);
      
      Shape3 = new ModelRenderer(this, 26, 19);
      Shape3.addBox(0F, 0F, 0F, 2, 2, 2);
      Shape3.setRotationPoint(-6F, 9F, 6F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0.7853982F);
      Shape4 = new ModelRenderer(this, 26, 0);
      Shape4.addBox(0F, 0F, 0F, 2, 6, 2);
      Shape4.setRotationPoint(-7.4F, 10.4F, 6F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
    
      Shape5 = new ModelRenderer(this, 26, 19);
      Shape5.addBox(0F, 0F, 0F, 2, 2, 2);
      Shape5.setRotationPoint(6F, 9F, 6F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0.7853982F);
     
     
      Shape6 = new ModelRenderer(this, 26, 0);
      Shape6.addBox(0F, 0F, 0F, 2, 6, 2);
      Shape6.setRotationPoint(5.4F, 10.4F, 6F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
    
      head = new ModelRenderer(this, 37, 0);
      head.addBox(-4F, -7F, -2F, 12, 8, 2);
      head.setRotationPoint(-2F, 16F, 8F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      feet = new ModelRenderer(this, 0, 24);
      feet.addBox(-2F, 0F, -2F, 12, 7, 10);
      feet.setRotationPoint(-4F, 17F, 0F);
      feet.setTextureSize(128, 64);
      feet.mirror = true;
      setRotation(feet, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 0);
      Shape7.addBox(0F, 0F, 0F, 2, 9, 10);
      Shape7.setRotationPoint(-8F, 15F, -2F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 25, 9);
      Shape8.addBox(0F, 0F, 0F, 2, 7, 2);
      Shape8.setRotationPoint(-8F, 16.4F, -3.4F);
      Shape8.setTextureSize(128, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 0);
      Shape9.addBox(0F, 0F, 0F, 2, 9, 10);
      Shape9.setRotationPoint(6F, 15F, -2F);
      Shape9.setTextureSize(128, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 25, 9);
      Shape10.addBox(0F, 0F, 0F, 2, 7, 2);
      Shape10.setRotationPoint(6F, 16.4F, -3.4F);
      Shape10.setTextureSize(128, 64);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 25, 9);
      Shape11.addBox(0F, 0F, 0F, 2, 7, 2);
      Shape11.setRotationPoint(-8F, 17F, -3.4F);
      Shape11.setTextureSize(128, 64);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 25, 9);
      Shape12.addBox(0F, 0F, 0F, 2, 7, 2);
      Shape12.setRotationPoint(6F, 17F, -3.4F);
      Shape12.setTextureSize(128, 64);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    head.render(f5);
    feet.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ll)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, ll);
  }


	 public void renderModel(float f1)
	  {
		  Shape1.render(f1);
		  Shape2.render(f1);
		  Shape3.render(f1);
		  Shape4.render(f1);
		  Shape5.render(f1);
		  Shape6.render(f1);
		  head.render(f1);
		  feet.render(f1);
		  Shape7.render(f1);
		  Shape8.render(f1);
		  Shape9.render(f1);
		  Shape10.render(f1);
	      Shape11.render(f1);
	      Shape12.render(f1);
	  }
	
}


